# Generated by Django 2.2 on 2019-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
