# Generated by Django 2.2 on 2019-04-24 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_method_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ТАӘ')),
                ('oblis', models.CharField(max_length=255, verbose_name='Облыс')),
                ('city', models.CharField(max_length=255, verbose_name='Кала')),
                ('description', models.TextField(verbose_name='Өтініш мақсаты')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Method')),
            ],
            options={
                'verbose_name': 'Өтініш',
                'verbose_name_plural': 'Өтініш',
            },
        ),
    ]
